server:
  port: 8080
  host: "0.0.0.0"
  debug: true

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "miniflow"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # seconds

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "miniflow-secret-key-change-in-production"
  expires_hours: 24

log:
  level: "info"
  format: "json"
  output: "stdout"
